### PR TITLE
session2 - kb review

### PR DESCRIPTION
**Pull request by kbjarkefur**
@kbjarkefur 's suggestions to session 2

### CODE REVIEW

**Comment by kbjarkefur** [comment]
When presenting you probably want to avoid using a big monitor as many participants will connect using laptops. You might even still have to zoom in 150% so that is shows well even with slightly reduces quality when shared in video call. Therefore I wrapped long text in code cells in 1de05b687610dabb7d33f9eefa6b2aa10ed7ba78 (Markdown wrap automatically even when zooming.)

**Comment by kbjarkefur** [comment]
`import math` was included in a cell where it did not seem necessary. So I removed it in: cce1fb185a435ae9d7ba8ae13d31ff6b3f256af9

Did I miss understand something? It was in cell:
```
## Let's list some built-in functions
print("This is an example of a built in function")
print("The string 'Mississippi' has {} cahracters".format(len('Mississippi')))
print("Sorted version of list [7,8,1,4,2] is {}".format(sorted([7,8,1,4,2])))
```

**Comment by kbjarkefur** [comment]
I moved the png files to a subfolder called `img` in 0eb3519e72876627d33ded295c8ce5cb2c5da30b and restored the ignore file. Happy to talk about the `ignore` template if you want

**Comment by gauravcusp** [comment]
Thanks Kris!! These have been addressed in Session 2 branch.

**Pull request closed without merging**
